#!/usr/bin/env python3
"""Phase 6 — Story Engine & Narrative Intelligence System verification + report.

Verifies the story engine against the `StoryEngine/` markdown guides, generates
sample episodes and a season plan, validates every episode, and writes
`PHASE6_REPORT.md`.

Reproduction:
    python scripts/generate_phase6.py
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.story_engine import (
    check_docs,
    quality_checklist,
    CurriculumEngine,
    ThemeEngine,
    LearningObjectiveEngine,
    CharacterEngine,
    WorldEngine,
    StoryGrammarLibrary,
    ConflictEngine,
    EpisodeGenerator,
    StoryValidationEngine,
    SeriesPlanner,
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docs-dir", default="StoryEngine",
                        help="Directory containing the StoryEngine/ markdown guides")
    parser.add_argument("--out", default="PHASE6_REPORT.md",
                        help="Output report path")
    parser.add_argument("--episodes", type=int, default=5,
                        help="Number of sample episodes to generate")
    args = parser.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    docs_dir = args.docs_dir
    if not os.path.isabs(docs_dir):
        docs_dir = os.path.join(root, docs_dir)

    doc_report = check_docs(docs_dir)
    d = doc_report.to_dict()

    curriculum = CurriculumEngine()
    themes = ThemeEngine()
    objectives = LearningObjectiveEngine()
    characters = CharacterEngine()
    world = WorldEngine()
    grammars = StoryGrammarLibrary()
    conflicts = ConflictEngine()
    generator = EpisodeGenerator()
    validation = StoryValidationEngine()
    planner = SeriesPlanner()

    episodes = [
        generator.generate_episode(season=1, episode_number=i + 1,
                                   target_age="2-5", difficulty=((i % 3) + 1))
        for i in range(args.episodes)
    ]
    validated = [validation.validate(ep) for ep in episodes]
    all_valid = all(len(issues) == 0 for issues in validated)

    season_plan = planner.plan_season(season_number=1, episode_count=args.episodes,
                                      generator=generator)

    lines = [
        "# Phase 6 Report — Story Engine & Narrative Intelligence System",
        "",
        f"> Generated by `scripts/generate_phase6.py` on docs at `{docs_dir}`.",
        "",
        "## Doc <-> Code Consistency",
        "",
        f"- **Facts checked:** {d['facts_checked']}",
        f"- **Facts passed:** {d['facts_passed']}",
        f"- **Overall:** {'PASS' if d['passed'] else 'FAIL'}",
        f"- **Missing files:** {', '.join(d['missing_files']) or 'none'}",
        f"- **Failed facts:** {', '.join(d['facts_failed']) or 'none'}",
        "",
        "## Library Inventory",
        "",
        f"- Curriculum areas: {len(curriculum.list_areas())}",
        f"- Themes: {len(themes._themes)}",
        f"- Learning objectives: {len(objectives._objectives)}",
        f"- Characters: {len(characters._characters)}",
        f"- Locations: {len(world.get_all_locations())} across "
        f"{len(world.get_all_zones())} zones",
        f"- Conflicts: {len(conflicts.conflicts)}",
        f"- Story grammars: {len(grammars.list_grammars())}",
        "",
        "## Sample Episodes",
        "",
        "| ID | Title | Area | Objective | Theme | Location | Grammar |",
        "|----|-------|------|-----------|-------|----------|---------|",
    ]
    for ep in episodes:
        lines.append(
            f"| {ep.episode_id} | {ep.title} | {ep.curriculum_area} | "
            f"{ep.learning_objective} | {ep.theme} | {ep.location} | "
            f"{ep.story_grammar} |"
        )

    lines += [
        "",
        "## Episode Validation",
        "",
    ]
    for ep, issues in zip(episodes, validated):
        lines.append(f"- **{ep.episode_id}:** {'PASS' if not issues else 'FAIL — ' + '; '.join(issues)}")

    lines += [
        "",
        "## Season Plan (Season 1)",
        "",
        f"- **Season title:** {season_plan.title}",
        f"- **Episodes planned:** {len(season_plan.episodes)}",
        f"- **Curriculum focus:** {', '.join(season_plan.curriculum_focus)}",
        "",
        "## Quality Checklist",
        "",
    ]
    lines += [f"- [ ] {check}" for check in quality_checklist()]
    lines += ["", "## Summary", ""]
    lines.append(
        f"- **Libraries encoded:** {len(curriculum.list_areas())} curriculum areas, "
        f"{len(objectives._objectives)} objectives, {len(themes._themes)} themes, "
        f"{len(characters._characters)} characters, {len(world.get_all_locations())} "
        f"locations, {len(conflicts.conflicts)} conflicts, "
        f"{len(grammars.list_grammars())} grammars."
    )
    lines.append(
        f"- **Doc consistency:** {d['facts_passed']}/{d['facts_checked']} facts verified "
        f"against the StoryEngine/ markdown guides."
    )
    lines.append(
        f"- **Generation:** {len(episodes)} sample episodes generated; "
        f"{'all' if all_valid else 'some'} pass StoryValidationEngine validation."
    )
    lines.append(
        f"- **Series planner:** Season 1 '{season_plan.title}' planned with "
        f"{len(season_plan.episodes)} episodes."
    )

    out_path = args.out
    if not os.path.isabs(out_path):
        out_path = os.path.join(root, out_path)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"Doc consistency: {d['facts_passed']}/{d['facts_checked']} facts passed")
    print(f"Episodes:        {len(episodes)} generated, "
          f"validated={all_valid}")
    print(f"Season 1:        {len(season_plan.episodes)} episodes planned")
    print(f"Report written:  {out_path}")
    return 0 if d["passed"] and all_valid else 1


if __name__ == "__main__":
    sys.exit(main())
