#!/usr/bin/env python3
"""Phase 4 — Animation Bible & Motion System verification + report.

Verifies the machine-readable animation bible against the `Animation/`
markdown docs, resolves every motion in the cycle library into a MotionBrief,
validates a batch of sample plans through the full motion system, and writes
`PHASE4_REPORT.md`.

Reproduction:
    python scripts/generate_phase4.py
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.animation import (
    AnimationClip, MotionCategory, FacialExpression, CameraMotion,
)
from src.animation_bible import AnimationBible, MotionSystem, quality_checklist


def _sample_plans(system: MotionSystem):
    specs = [
        dict(shot_id="SH_001", motion=MotionCategory.IDLE, expression=FacialExpression.HAPPY,
             camera_motion=CameraMotion.STATIC, dialogue="", duration_seconds=3.0),
        dict(shot_id="SH_002", motion=MotionCategory.WALK, expression=FacialExpression.CURIOUS,
             camera_motion=CameraMotion.TRACK, dialogue="Let's go to the park!",
             duration_seconds=4.0),
        dict(shot_id="SH_003", motion=MotionCategory.RUN, expression=FacialExpression.EXCITED,
             camera_motion=CameraMotion.FOLLOW, dialogue="", duration_seconds=2.0),
        dict(shot_id="SH_004", motion=MotionCategory.DANCE, expression=FacialExpression.LAUGHING,
             camera_motion=CameraMotion.STATIC, dialogue="la la la!", duration_seconds=3.0),
        dict(shot_id="SH_005", motion=MotionCategory.JUMP, expression=FacialExpression.SURPRISED,
             camera_motion=CameraMotion.STATIC, dialogue="", duration_seconds=1.5),
        dict(shot_id="SH_006", motion=MotionCategory.SLEEP, expression=FacialExpression.NEUTRAL,
             camera_motion=CameraMotion.STATIC, dialogue="", duration_seconds=5.0),
        dict(shot_id="SH_007", motion=MotionCategory.CLAP, expression=FacialExpression.HAPPY,
             camera_motion=CameraMotion.STATIC, dialogue="", duration_seconds=2.0),
        dict(shot_id="SH_008", motion=MotionCategory.READ, expression=FacialExpression.THOUGHTFUL,
             camera_motion=CameraMotion.PUSH_IN, dialogue="", duration_seconds=4.0),
    ]
    return [system.planner.plan_shot(**s) for s in specs]


def _sample_clips():
    return [
        AnimationClip(clip_id="CLIP_001", episode="S01E01", characters=["lily"],
                      environment="park", animation_type=MotionCategory.WALK,
                      duration_seconds=3.0, frame_rate=24, prompt_version="V4", seed=42),
        AnimationClip(clip_id="CLIP_002", episode="S01E01", characters=["benny"],
                      environment="playground", animation_type=MotionCategory.DANCE,
                      duration_seconds=3.0, frame_rate=30, prompt_version="V4", seed=7),
        AnimationClip(clip_id="CLIP_BAD", episode="S01E01", characters=["lily"],
                      environment="park", animation_type=MotionCategory.WALK,
                      duration_seconds=3.0, frame_rate=15, prompt_version="V4", seed=1),
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docs-dir", default="Animation",
                        help="Directory containing the Animation/ markdown bibles")
    parser.add_argument("--out", default="PHASE4_REPORT.md",
                        help="Output report path")
    args = parser.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    docs_dir = args.docs_dir
    if not os.path.isabs(docs_dir):
        docs_dir = os.path.join(root, docs_dir)

    bible = AnimationBible()
    system = MotionSystem()

    doc_report = bible.check_docs(docs_dir)

    briefs = [
        bible.build_motion_brief(motion=m, duration_seconds=3.0)
        for m in bible.list_motions()
    ]

    plans = _sample_plans(system)
    results = system.resolve_many(plans, character="Lily Bunny",
                                  environment="Sunny Garden Playground")
    plan_passed = sum(1 for r in results if r.ready)

    clip_results = [bible.validate_clip(c) for c in _sample_clips()]
    clip_passed = sum(1 for r in clip_results if r["passed"])

    lines = [
        "# Phase 4 Report — Animation Bible & Motion System",
        "",
        f"> Generated by `scripts/generate_phase4.py` on docs at `{docs_dir}`.",
        "",
        "## Doc <-> Code Consistency",
        "",
        f"- **Facts checked:** {doc_report.to_dict()['facts_checked']}",
        f"- **Facts passed:** {doc_report.to_dict()['facts_passed']}",
        f"- **Overall:** {'PASS' if doc_report.passed else 'FAIL'}",
        f"- **Missing files:** {', '.join(doc_report.missing_files) or 'none'}",
        f"- **Failed facts:** {', '.join(doc_report.to_dict()['facts_failed']) or 'none'}",
        "",
        "## Motion Cycle Library (resolved briefs at 3.0s / 24 fps)",
        "",
        "| Motion | Cycle frames | Loops | Cycles | Blink | Camera shot | Expression |",
        "|--------|--------------|-------|--------|-------|-------------|------------|",
    ]
    for b in briefs:
        lines.append(
            f"| {b.motion} | {b.frames_per_cycle} | {'yes' if b.loopable else 'no'} "
            f"| {b.cycles} | {b.blink} | {b.camera_shot} | {b.expression} |"
        )

    lines += [
        "",
        "## Motion System Validation (8 sample shots)",
        "",
        "| Shot | Motion | Bible | Pipeline | Ready | Prompt |",
        "|------|--------|-------|----------|-------|--------|",
    ]
    for r in results:
        lines.append(
            f"| {r.plan.shot_id} | {r.brief.motion} | "
            f"{'PASS' if r.bible_validation['passed'] else 'FAIL'} | "
            f"{'PASS' if r.pipeline_validation.passed else 'FAIL'} | "
            f"{'yes' if r.ready else 'no'} | `{r.prompt[:60]}...` |"
        )

    lines += [
        "",
        f"- **Plans passing bible + pipeline:** {plan_passed}/{len(plans)}",
        "",
        "## Clip Validation (frame rate / motion)",
        "",
        "| Clip | Frame rate | Animation | Passed |",
        "|------|-----------|-----------|--------|",
    ]
    for clip, result in zip(_sample_clips(), clip_results):
        lines.append(
            f"| {clip.clip_id} | {clip.frame_rate} | {clip.animation_type.value} | "
            f"{'yes' if result['passed'] else 'no'} |"
        )
    lines += [
        "",
        f"- **Clips passing:** {clip_passed}/{len(clip_results)}",
        "",
        "## Library Inventory",
        "",
        f"- Motions: {len(bible.list_motions())}",
        f"- Walk variants: {len(bible.list_walk_variants())} | "
        f"Run variants: {len(bible.list_run_variants())} | "
        f"Jumps: {len(bible.list_jumps())} | Dances: {len(bible.list_dances())}",
        f"- Expressions: {len(bible.list_expressions())} | "
        f"Gestures: {len(bible.list_gestures())} | "
        f"Interactions: {len(bible.list_interactions())}",
        f"- Camera shots: {len(bible.list_camera_shots())} | "
        f"Transitions: {len(bible.list_transitions())} | "
        f"Cloth elements: {len(bible.list_cloth_elements())}",
        "",
        "## Quality Checklist",
        "",
    ]
    lines += [f"- [ ] {check}" for check in quality_checklist()]
    lines += ["", "## Summary", ""]
    lines.append(
        f"- **Bible standards encoded:** {len(bible.list_motions())} motions, "
        f"{len(bible.list_expressions())} expressions, {len(bible.list_gestures())} gestures, "
        f"{len(bible.list_interactions())} interactions, {len(bible.list_camera_shots())} shots, "
        f"{len(bible.list_transitions())} transitions."
    )
    lines.append(
        f"- **Doc consistency:** {doc_report.to_dict()['facts_passed']}/"
        f"{doc_report.to_dict()['facts_checked']} facts verified against the markdown bibles."
    )
    lines.append(
        f"- **Motion system:** {plan_passed}/{len(plans)} sample plans fully validated "
        f"through bible + pipeline; {clip_passed}/{len(clip_results)} clips valid."
    )

    out_path = args.out
    if not os.path.isabs(out_path):
        out_path = os.path.join(root, out_path)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"Doc consistency: {doc_report.to_dict()['facts_passed']}/"
          f"{doc_report.to_dict()['facts_checked']} facts passed")
    print(f"Motion system:   {plan_passed}/{len(plans)} plans ready, "
          f"{clip_passed}/{len(clip_results)} clips valid")
    print(f"Report written:  {out_path}")
    return 0 if doc_report.passed and plan_passed == len(plans) else 1


if __name__ == "__main__":
    sys.exit(main())
