#!/usr/bin/env python3
"""Phase 5 — Audio Bible & Music Production System verification + report.

Verifies the machine-readable audio bible against the `Audio/` markdown docs,
resolves every song category and voice profile into a brief, builds a full
episode AudioPlan, and writes `PHASE5_REPORT.md`.

Reproduction:
    python scripts/generate_phase5.py
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.audio_bible import AudioBible, AudioProductionSystem, quality_checklist


def _sample_episode(system: AudioProductionSystem):
    return system.plan_episode(
        episode_id="S01E01",
        title="The Alphabet Garden",
        dialogue_lines=[
            ("Lily Bunny", "A is for apple! B is for ball!", "happy"),
            ("Ben Bear", "Yum yum, apples!", "excited"),
            ("Daisy Duck", "Quack quack, let's learn!", "cheerful"),
        ],
        songs=[
            ("Alphabet", "letter sounds", "Short"),
            ("Dance Songs", "moving and dancing", "Standard"),
            ("Bedtime", "sleepy time", "Short"),
        ],
        scene="Sunny Garden Playground",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docs-dir", default="Audio",
                        help="Directory containing the Audio/ markdown bibles")
    parser.add_argument("--out", default="PHASE5_REPORT.md",
                        help="Output report path")
    args = parser.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    docs_dir = args.docs_dir
    if not os.path.isabs(docs_dir):
        docs_dir = os.path.join(root, docs_dir)

    bible = AudioBible()
    system = AudioProductionSystem()

    doc_report = bible.check_docs(docs_dir)

    music_briefs = [
        bible.build_music_brief(category=c, topic=f"{c.lower()} fun",
                                duration_label="Standard")
        for c in bible.list_song_categories()
    ]
    voice_briefs = [
        bible.build_voice_brief(name) for name in bible.list_voice_profiles()
    ]

    plan = _sample_episode(system)
    episode_validation = system.validate_episode(plan)

    lines = [
        "# Phase 5 Report — Audio Bible & Music Production System",
        "",
        f"> Generated by `scripts/generate_phase5.py` on docs at `{docs_dir}`.",
        "",
        "## Doc <-> Code Consistency",
        "",
        f"- **Facts checked:** {doc_report.to_dict()['facts_checked']}",
        f"- **Facts passed:** {doc_report.to_dict()['facts_passed']}",
        f"- **Overall:** {'PASS' if doc_report.passed else 'FAIL'}",
        f"- **Missing files:** {', '.join(doc_report.missing_files) or 'none'}",
        f"- **Failed facts:** {', '.join(doc_report.to_dict()['facts_failed']) or 'none'}",
        "",
        "## Song Library (all 24 categories, Standard duration)",
        "",
        "| Category | Tempo | Duration | Structure |",
        "|----------|-------|----------|-----------|",
    ]
    for brief in music_briefs:
        lines.append(
            f"| {brief.category} | {brief.tempo} BPM | {brief.duration_label} "
            f"({brief.duration_seconds}s) | {len(brief.structure)} sections |"
        )

    lines += [
        "",
        "## Voice Profiles (11)",
        "",
        "| Character | Role | Pitch | Energy | TTS Engine |",
        "|-----------|------|-------|--------|------------|",
    ]
    for brief in voice_briefs:
        lines.append(
            f"| {brief.character} | {brief.role} | {brief.pitch} | "
            f"{brief.energy} | {brief.tts_engine} |"
        )

    lines += [
        "",
        "## Episode Audio Plan (sample: S01E01 — The Alphabet Garden)",
        "",
        f"- **Passed:** {'yes' if plan.passed else 'no'}",
        f"- **Narration:** {plan.narration.character if plan.narration else 'none'}",
        f"- **Dialogue clips:** {len(plan.dialogue)} ({plan.total_dialogue_seconds:.1f}s total)",
        f"- **Songs:** {len(plan.songs)} ({plan.total_song_seconds}s total)",
        f"- **SFX:** {', '.join(plan.sfx)}",
        f"- **Foley:** {', '.join(plan.foley)}",
        f"- **Ambience:** {', '.join(plan.ambience)}",
        f"- **Mix rules:** {len(plan.mix_rules)} applied",
        f"- **Master rules:** {len(plan.master_rules)} applied",
        f"- **Localization:** {', '.join(plan.localization)}",
        "",
        "| # | Speaker / Song | Type | Validation |",
        "|---|----------------|------|-----------|",
    ]
    for i, clip in enumerate(plan.dialogue, start=1):
        passed = "PASS" if clip.validation.get("passed") else "FAIL"
        phonemes = clip.lip_sync.total_phonemes() if clip.lip_sync else 0
        lines.append(
            f"| {i} | {clip.speaker}: \"{clip.text[:40]}\" | dialogue "
            f"({phonemes} phonemes) | {passed} |"
        )
    for i, entry in enumerate(plan.songs, start=1):
        passed = "PASS" if entry.validation.get("passed") else "FAIL"
        lines.append(
            f"| {i + len(plan.dialogue)} | {entry.category}: {entry.topic[:40]} "
            f"| song ({entry.brief.duration_seconds}s) | {passed} |"
        )
    lines += [
        "",
        f"- **Episode validation:** {episode_validation['violations'] or 'no violations'}; "
        f"{episode_validation['warnings'] or 'no warnings'}",
        "",
        "## Library Inventory",
        "",
        f"- Song categories: {len(bible.list_song_categories())} | "
        f"Sections: {len(bible.list_song_sections())} | Durations: {len(bible.list_durations())}",
        f"- Voice profiles: {len(bible.list_voice_profiles())} | "
        f"Pronunciations: {len(bible.list_pronunciations())}",
        f"- Sound effects: {len(bible.list_sound_effects())} | "
        f"Foley: {len(bible.list_foley_sounds())} | Ambience: {len(bible.list_ambience())}",
        f"- Mixing rules: {len(bible.mixing_rules())} | "
        f"Mastering rules: {len(bible.mastering_rules())} | "
        f"Lip-sync standards: {len(bible.lipsync_standards())} | "
        f"Localization standards: {len(bible.localization_standards())}",
        "",
        "## Quality Checklist",
        "",
    ]
    lines += [f"- [ ] {check}" for check in quality_checklist()]
    lines += ["", "## Summary", ""]
    lines.append(
        f"- **Audio standards encoded:** {len(bible.list_song_categories())} song "
        f"categories, {len(bible.list_voice_profiles())} voice profiles, "
        f"{len(bible.list_sound_effects())} SFX, {len(bible.list_foley_sounds())} foley, "
        f"{len(bible.list_ambience())} ambient beds, {len(bible.list_pronunciations())} pronunciations."
    )
    lines.append(
        f"- **Doc consistency:** {doc_report.to_dict()['facts_passed']}/"
        f"{doc_report.to_dict()['facts_checked']} facts verified against the markdown bibles."
    )
    lines.append(
        f"- **Production system:** episode '{plan.episode_id}' assembled with "
        f"{len(plan.dialogue)} dialogue clips (phoneme lip-sync at 24 fps) and "
        f"{len(plan.songs)} songs; {'passes' if plan.passed else 'fails'} validation."
    )

    out_path = args.out
    if not os.path.isabs(out_path):
        out_path = os.path.join(root, out_path)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"Doc consistency: {doc_report.to_dict()['facts_passed']}/"
          f"{doc_report.to_dict()['facts_checked']} facts passed")
    print(f"Episode plan:    {plan.episode_id} -> "
          f"{len(plan.dialogue)} dialogue clips, {len(plan.songs)} songs, "
          f"passed={plan.passed}")
    print(f"Report written:  {out_path}")
    return 0 if doc_report.passed and plan.passed else 1


if __name__ == "__main__":
    sys.exit(main())
